name: Hourly Link Update

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download, format and encode whole file
      run: |
        echo "#profile-update-interval: 1" > temp.txt
        echo "#hide-settings: 1" >> temp.txt
        echo "#profile-title: 🪐 Pure VPN | ТЕСТ" >> temp.txt
        echo "#subscription-userinfo: upload=0; download=0; total=0; expire=1782853200" >> temp.txt
        echo "#support-url: https://pure-vpn.qwvexm.ru" >> temp.txt
        echo "#announce: base64:4oS577iPINCt0YLQviDRgtC10YHRgtC+0LLRi9C1INGB0LXRgNCy0LXRgNCwLCDQt9C00LXRgdGMINGB0L7QsdGA0LDQvdGLINC60LDQuiDRgNCw0LHQvtGH0LjQtSDRgtCw0Log0Lgg0L3QtdGA0LDQsdC+0YfQuNC1LiDQntCx0L3QvtCy0LvRj9C10YLRgdGPINGA0LDQtyDQsiDRh9Cw0YEuCgpwdXJlLXZwbi5xd3ZleG0ucnU=" >> temp.txt

        curl -sL "https://raw.githubusercontent.com/zieng2/wl/refs/heads/main/vless_lite.txt" | tail -n +5 | head -n 31 >> temp.txt
        curl -sL "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/Vless-Reality-White-Lists-Rus-Mobile-2.txt" | tail -n +7 | head -n 21 >> temp.txt
        cat temp.txt | base64 -w 0 > links.txt
        rm temp.txt

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@://github.com"
        git add links.txt
        git diff-index --quiet HEAD || git commit -m "Automated links update from two sources [skip ci]"
        git push
