name: Hourly Link Update

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download, format and encode whole file
      run: |
        # 1. Записываем служебные заголовки во временный файл
        echo "#profile-update-interval: 1" > temp.txt
        echo "#hide-settings: 1" >> temp.txt
        echo "#profile-title: 🪐 Pure VPN | ТЕСТ" >> temp.txt
        echo "#subscription-userinfo: expire=1782853200" >> temp.txt
        echo "#support-url: https://pure-vpn.qwvexm.ru" >> temp.txt
        echo "#announce: base64:4oS577iPINCi0LXRgdGC0L7QstGL0LUg0YHQtdGA0LLQtdGA0LAKCuKsh++4jyDQndCwINGB0LDQudGC0LUg0LXRgdGC0Ywg0YDQtdGI0LXQvdC40LUg0LXRgdC70Lgg0L/QuNC90LMg0LHQvtC70YzRiNC1IDk5OdC80YEg4qyH77iPCnB1cmUtdnBuLnF3dmV4bS5ydQ==" >> temp.txt
        
        # 2. Скачиваем ссылки со всех источников в один черновой файл raw.txt
        curl -sL "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/Vless-Reality-White-Lists-Rus-Mobile.txt" | tail -n +7 | head -n 35 > raw.txt
        curl -sL "https://raw.githubusercontent.com/zieng2/wl/refs/heads/main/vless_lite.txt" | tail -n +5 | head -n 34 >> raw.txt
        
        # 3. Переименовываем каждую строчку по вашему новому шаблону
        awk '
        BEGIN {
            counter = 1
        }
        /vless:\/\// {
            split($0, parts, "#")
            print parts[1] "#🇷🇺 🛜 WIFI • ТЕСТ #" counter
            counter++
        }
        ' raw.txt >> temp.txt
        
        # 4. Кодируем итоговый файл целиком в base64 без переносов строк
        cat temp.txt | base64 -w 0 > links.txt
        
        # Удаляем временные файлы
        rm temp.txt raw.txt

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add links.txt
        git diff-index --quiet HEAD || git commit -m "Automated links update with WIFI layout [skip ci]"
        git push
